stages:
  - build
  - deploy

build-gradle:
  stage: build
  image: adoptopenjdk/openjdk11:x86_64-alpine-jdk11u-2021-09-03-02-30-beta-nightly-slim

  only:
    - develop
    - main
    - build-test

  variables:
   GRADLE_USER_HOME: '.gradle-cache' 
   GRADLE_OPTS: '-Dorg.gradle.daemon=false'

  cache:
    key: "$CI_JOB_NAME"
    paths:
      - $GRADLE_USER_HOME

  script:
    - cd contracktor
    - chmod +x gradlew
    - mkdir -p target
    - ./gradlew build
    - mv build/libs/contracktor-0.0.1-SNAPSHOT.jar target/app.jar

  artifacts:
    when:
      always
    reports:
      junit: contracktor/build/test-results/test/TEST-*.xml
    paths: 
      - contracktor/target/app.jar


docker-deploy:
  stage: deploy
  image: docker:latest

  only:
    - main
    - build-test

  script:
    - apk add --no-cache docker-compose
    - cd contracktor
    - docker-compose down
    - docker-compose rm -f
    - docker-compose build
    - docker-compose up -d
