version: "3"
services:
  bim-mock:
    image: sapza/bimcontracts-kiel-mock:latest
    ports:
      - "3000:3000"
    networks:
      apinet:
        ipv4_address: 172.18.0.5
  web:
    build:
      context: ./
      dockerfile: docker/app/Dockerfile
    ports:
        - "8080:8080"
    volumes:
        - db-volume:/data

    networks:
      apinet:
        ipv4_address: 172.18.0.6

volumes:
  db-volume:
    external: true

networks:
  apinet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1


